name: Python package

on: [push]
env:
  ALGORITHM: HS256
  MONGODB_URI: mongodb+srv://Admin:8MrBpwzzaP5mTlD4@cluster0.lahb0.mongodb.net/kisaragi-auth?retryWrites=true&w=majority
  SECRET_KEY: 21429ad6d71399e617f7f4d5e6f53454
  CODECOV_TOKEN: 87d7f11b-8c6d-49b4-8195-31322ce8c52f
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}